[providers.aihubmix]
outputToPiModelsJson = true
authHeader = true
models = ["cc-minimax-m2.5", "cc-glm-5", "kimi-k2.5"]

[providers.aihubmix.model."cc-minimax-m2.5"]
name = "Claude Code MiniMax-M2.5"
compat = { supportsDeveloperRole = false }

[providers.aihubmix.model."cc-glm-5"]
name = "Claude Code GLM-5"
compat = { supportsDeveloperRole = false }

[providers.aihubmix.model."kimi-k2.5"]
name = "Kimi K2.5"
compat = { supportsDeveloperRole = false }

[providers.opencode]
outputToPiModelsJson = false
models = [
  # "kimi-k2.5-free", Rate limits quickly exceeded
  # "minimax-m2.1-free", Very high latency
  "trinity-large-preview-free",
]

[providers.openrouter]
outputToPiModelsJson = true
models = [
  "arcee-ai/trinity-large-preview:free",
  "stepfun/step-3.5-flash:free",
  "@preset/kimi25-high-reasoning", # Manually created preset to prefer providers with higher throughput
]

[providers.cerebras]
outputToPiModelsJson = false
models = ["qwen-3-235b-a22b-instruct-2507"]

[providers.google]
outputToPiModelsJson = false
models = ["gemini-3-flash-preview"]
