{
  inputs,
  ...
}:
{
  imports = [
    inputs.disko.nixosModules.disko
    inputs.sops-nix.nixosModules.sops
    ../../modules/disko-partitions.nix
    ../../modules/core.nix
    ../../modules/nix.nix
    ../../modules/nh.nix
    ../../modules/user.nix
    ../../modules/openssh-server.nix
    ../../modules/security.nix
    ../../modules/tailscale.nix
    ../../modules/vector.nix
    ../../modules/gh.nix
    ./my-config.nix
  ];
}
