local function write_blog_markdown(lang)
  vim.cmd(':Neorg inject-metadata')
  vim.cmd(':w')

  local filename_template = '%s.md'
  if lang == 'ja' then
    filename_template = '%s.ja.md'
  end
  local markdown_filename = vim.fn.fnameescape(string.format(filename_template, vim.fn.expand('%:t:r')))
  local markdown_path = '/Users/norman/code/blog/content/blog/' .. markdown_filename
  vim.cmd(':Neorg export to-file ' .. markdown_path)
  vim.cmd('vsplit')
  local win = vim.api.nvim_get_current_win()
  local buf = vim.api.nvim_create_buf(true, true)
  vim.api.nvim_win_set_buf(win, buf)

  vim.cmd('e ' .. markdown_path)

  -- Change metadata delimiters from Neorg to Zola format
  vim.cmd([[:%s/^title:/title =/]])
  vim.cmd([[:%s/^date:/date =/]])

  -- [Neorg%203.md](#neorg203md) -> [Neorg%203.md]
  vim.cmd([[:%s/(#.*md)//ge]])

  if lang == 'ja' then
    -- [Neorg%203.md] -> (@/blog/Neorg%203.ja.md)
    vim.cmd([[:%s/\[\(.*\).md\]/(@\/blog\/\1.ja.md)/ge]])
  else
    -- [Neorg%203.md] -> (@/blog/Neorg%203.md)
    vim.cmd([[:%s/\[\(.*\).md\]/(@\/blog\/\1.md)/ge]])
  end

  -- (@/blog/Neorg%203.md) -> [Neorg%203](@/blog/Neorg%203.md)
  vim.cmd([[:%s/(@\/blog\/\(.*\).md)/[\1]\0/ge]])

  -- TODO(norman): Figure out how to unescape text in the [label]

  vim.cmd(':w')

  vim.cmd(':Git add -A')

  local now = os.date('%Y-%m-%d %X')
  vim.cmd(string.format(':Git commit -m "content(blog): %s autogenerated Markdown"', now))
end

local function configure_neorg()
  require('neorg').setup({
    load = {
      ['core.defaults'] = {},
      ['core.keybinds'] = {
        config = {
          default_keybinds = true,
          neorg_leader = '<Leader>o',
        },
      },
      ['core.concealer'] = {
        config = {
          folds = false,
          icon_preset = 'diamond',
          icons = {
            todo = {
              undone = { icon = ' ' },
              done = { icon = '✔' },
              uncertain = { icon = '?' },
              urgent = { icon = '!' },

              cancelled = { icon = '_' },
              on_hold = { icon = '=' },
              pending = { icon = '-' },
            },
          }
        },
      },
      ['core.manoeuvre'] = {},
      ['core.journal'] = {
        config = {
          strategy = 'flat',
          journal_folder = '',
          use_template = false,
          workspace = 'notes',
          open_last_workspace = true,
          use_popup = true,
        }
      },
      ['core.dirman'] = {
        config = {
          workspaces = {
            notes = '~/code/notes',
          },
          default_workspace = 'notes',
          autochdir = true,
          index = 'index.norg',
        },
      },
      ['core.completion'] = {
        config = {
          engine = 'nvim-cmp',
        },
      },
      ['core.presenter'] = {
        config = {
          zen_mode = 'truezen',
        },
      },
      ['core.esupports.metagen'] = {
        config = {
          -- One of "none", "auto" or "empty"
          -- - "none" generates no metadata
          -- - "auto" generates metadata if it is not present
          -- - "empty" generates metadata only for new files/buffers.
          type = 'empty',

          -- Whether updated date field should be automatically updated on save if required
          update_date = false,

          template = {
            {
              'title',
              function()
                return string.format('"%s"', vim.fn.expand('%:p:t:r'))
              end,
            },

            {
              'date',
              function()
                return os.date('%Y-%m-%d')
              end,
            },
          },

        },
      },
      ['core.summary'] = {
        config = {
          strategy = 'metadata',
        },
      },
      ['core.export'] = {
        config = {},
      },
      ['core.export.markdown'] = {
        config = {
          extensions = 'all',
          metadata = {
            ['start'] = '+++',
            ['end'] = '+++',
          },
        },
      },
    },
  })
end

return {
  'nvim-neorg/neorg',
  dependencies = {
    { 'nvim-lua/plenary.nvim' },
    { 'Pocco81/true-zen.nvim' },
  },
  keys = {
    { '<Leader>ni', '<Cmd>Neorg index<CR>' },
    { '<Leader>ei', '<Cmd>Neorg index<CR>' },
    { '<Leader>en', '<Cmd>Neorg journal today<CR>' },
    { '<Leader>er', '<Cmd>Neorg return<CR>' },

    { '<Leader>nc', '<Cmd>Neorg toggle-concealer<CR>' },

    { '<Leader>mcb', '<Cmd>Neorg keybind all core.looking-glass.magnify-code-block<CR>' },

    { '<Leader>mb',
      function()
        write_blog_markdown('en')
      end,
      desc = 'Deploy this English post to my blog',
    },

    { '<Leader>mjb',
      function()
        write_blog_markdown('ja')
      end,
      desc = 'Deploy this Japanese post to my blog',
    },
  },
  config = configure_neorg,
  lazy = false,
  build = ':Neorg sync-parsers',
}
